[Do not merge]Add appnav tests
salesforce/utam-java-recipes pull request #26
Opened 2022-06-23 20:47 UTC by sivareddypv1

locally updated page objects used for the test. We will merge the test once the PO updates published to salesforce PO artifact.

2022-06-25 00:11 UTC, lizaiv77 requested changes
pls wait for new version 1.1.1 on https://mvnrepository.com/artifact/com.salesforce.utam/salesforce-pageobjects and address comments

2022-06-25 00:11 UTC, lizaiv77 commented on utam-tests/src/test/java/utam/examples/salesforce/web/AppNavigationTests.java
> +  private void openRecordModal(RecordType recordType) {
why this method is here? pls remove

2022-06-25 00:11 UTC, lizaiv77 commented on utam-tests/src/test/java/utam/examples/salesforce/web/AppNavigationTests.java
> +//    menu item with name 'Forecasts' should present in overflow items
code format pls

2022-06-25 00:11 UTC, lizaiv77 commented on utam-preview/src/main/resources/compiler.config.json
> +      "pathMatch": ".*/nav"
pls remove and replace all page objects by artifact

2022-06-27 17:39 UTC, sivareddypv1 commented on utam-tests/src/test/java/utam/examples/salesforce/web/AppNavigationTests.java
> +//    menu item with name 'Forecasts' should present in overflow items
formatted

2022-06-27 21:25 UTC, merged